import 'package:flutter/material.dart';

class Language {
  final String name;
  final String code;

  Language(this.name, this.code);
}

List<Language> languages = [
  Language('Afrikaans', 'af'),
  Language('Albanian', 'sq'),
  Language('Amharic', 'am'),
  Language('Arabic', 'ar'),
  Language('Armenian', 'hy'),
  Language('Azerbaijani', 'az'),
  Language('Basque', 'eu'),
  Language('Bengali', 'bn'),
  Language('Bosnian', 'bs'),
  Language('Bulgarian', 'bg'),
  Language('Burmese', 'my'),
  Language('Catalan', 'ca'),
  Language('Central Khmer', 'km'),
  Language('Chinese', 'zh'),
  Language('Croatian', 'hr'),
  Language('Czech', 'cs'),
  Language('Danish', 'da'),
  Language('Dutch', 'nl'),
  Language('English', 'en'),
  Language('Estonian', 'et'),
  Language('Filipino', 'fil'),
  Language('Finnish', 'fi'),
  Language('French', 'fr'),
  Language('Galician', 'gl'),
  Language('Georgian', 'ka'),
  Language('German', 'de'),
  Language('Gujarati', 'gu'),
  Language('Hebrew', 'he'),
  Language('Hindi', 'hi'),
  Language('Hungarian', 'hu'),
  Language('Icelandic', 'is'),
  Language('Indonesian', 'id'),
  Language('Irish', 'ga'),
  Language('Italian', 'it'),
  Language('Japanese', 'ja'),
  Language('Javanese', 'jv'),
  Language('Kannada', 'kn'),
  Language('Kazakh', 'kk'),
  Language('Korean', 'ko'),
  Language('Lao', 'lo'),
  Language('Latvian', 'lv'),
  Language('Lithuanian', 'lt'),
  Language('Macedonian', 'mk'),
  Language('Malay (macrolanguage)', 'ms'),
  Language('Malayalam', 'ml'),
  Language('Maltese', 'mt'),
  Language('Mandarin Chinese', 'cmn'),
  Language('Marathi', 'mr'),
  Language('Modern Greek (1453-)', 'el'),
  Language('Mongolian', 'mn'),
  Language('Nepali (macrolanguage)', 'ne'),
  Language('Norwegian Bokmål', 'nb'),
  Language('Panjabi', 'pa'),
  Language('Persian', 'fa'),
  Language('Polish', 'pl'),
  Language('Portuguese', 'pt'),
  Language('Portuguese (Portugal)', 'pt_PT'),
  Language('Pushto', 'ps'),
  Language('Romanian', 'ro'),
  Language('Russian', 'ru'),
  Language('Serbian', 'sr'),
  Language('Sinhala', 'si'),
  Language('Slovak', 'sk'),
  Language('Slovenian', 'sl'),
  Language('Somali', 'so'),
  Language('Spanish', 'es'),
  Language('Standard Arabic', 'arb'),
  Language('Sundanese', 'su'),
  Language('Swahili (macrolanguage)', 'sw'),
  Language('Swedish', 'sv'),
  Language('Tamil', 'ta'),
  Language('Telugu', 'te'),
  Language('Thai', 'th'),
  Language('Turkish', 'tr'),
  Language('Ukrainian', 'uk'),
  Language('Urdu', 'ur'),
  Language('Uzbek', 'uz'),
  Language('Vietnamese', 'vi'),
  Language('Welsh', 'cy'),
  Language('Wu Chinese', 'wuu'),
  Language('Yue Chinese', 'yue'),
  Language('Zulu', 'zu'),
];

final List<DropdownMenuItem<String>> languageDropdownItems = languages
    .map(
      (language) => DropdownMenuItem<String>(
        value: language.code,
        child: Text(language.name),
      ),
    )
    .toList();
